=== spider4216/JavaLabEpam/com/epam/homework/task5/xml/schema/publication_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:complexType name="Paper">
		<xsd:sequence>
			<xsd:element name="item" type="Publication" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:complexType name="Publication">
		<xsd:sequence>
			<xsd:element name="title" type="xsd:string" />
			<xsd:element name="type" type="PublishType" />
			<xsd:element name="period" type="Period" />
			<xsd:element name="characteristic" type="Characteristic" maxOccurs="unbounded" />
			<xsd:element name="index" type="xsd:string" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="PublishType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="газета" />
			<xsd:enumeration value="журнал" />
			<xsd:enumeration value="буклет" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="Period">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ежедневно" />
			<xsd:enumeration value="еженедельно" />
			<xsd:enumeration value="ежемесячно" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="Characteristic">
		<xsd:sequence>
			<xsd:element name="color" type="ChColor" />
			<xsd:element name="volume" type="xsd:string" />
			<xsd:element name="gloss" type="ChGloss" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="ChColor">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Да" />
			<xsd:enumeration value="Нет" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:simpleType name="ChGloss">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Да" />
			<xsd:enumeration value="Нет" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:element name="paper" type="Paper"></xsd:element>
</xsd:schema>

=== spider4216/JavaLabEpam/com/epam/homework/task5/xml/source/publication.xml
<?xml version="1.0" encoding="UTF-8"?>
<paper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../publication_schema.xsd">
	<item>
		<title>New York Times</title>
		<type>газета</type>
		<period>еженедельно</period>
		<characteristic>
			<color>Да</color>
			<volume>1.2</volume>
			<gloss>Да</gloss>
		</characteristic>
		<index>1</index>
	</item>
	
	<item>
		<title>Time</title>
		<type>журнал</type>
		<period>еженедельно</period>
		<characteristic>
			<color>Да</color>
			<volume>1.2</volume>
			<gloss>Да</gloss>
		</characteristic>
	</item>
</paper>
